// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAgencyAPI.Data;

#nullable disable

namespace RealEstateAgencyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230801122046_SeedPropertyTable")]
    partial class SeedPropertyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAgencyAPI.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Stadiou Street 7",
                            City = "Kavos",
                            Country = "Greece",
                            CreatedDate = new DateTime(2023, 8, 1, 14, 20, 45, 855, DateTimeKind.Local).AddTicks(1959),
                            Details = "50 meters from the beach",
                            ImageURL = "https://i.pinimg.com/1200x/4d/37/32/4d37324143b5f5a0ecca431b66a60e12.jpg",
                            Name = "Beach House",
                            SquareMeters = 76.0,
                            Type = "House"
                        },
                        new
                        {
                            Id = 2,
                            Address = "9th Avenue 143",
                            City = "New York City",
                            Country = "United States of America",
                            CreatedDate = new DateTime(2023, 8, 1, 14, 20, 45, 855, DateTimeKind.Local).AddTicks(1986),
                            Details = "5th floor",
                            ImageURL = "https://images1.apartments.com/i2/gV9g9N4i55VYrA8JKF-ECZVproGO3WaVB8FQpuKY7DQ/111/746-9th-ave-new-york-ny-primary-photo.jpg",
                            Name = "NYC Appartment",
                            SquareMeters = 83.0,
                            Type = "Appartment"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Partizanska 34",
                            City = "Novi Sad",
                            Country = "Serbia",
                            CreatedDate = new DateTime(2023, 8, 1, 14, 20, 45, 855, DateTimeKind.Local).AddTicks(2003),
                            Details = "Suburbs of Novi Sad",
                            ImageURL = "https://m3.spitogatos.gr/259892801_300x220.jpg?v=20130730",
                            Name = "Industrial warehouse",
                            SquareMeters = 3267.0,
                            Type = "Warehouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
